"""Subclass of PreferencesDialog, which is generated by wxFormBuilder."""

import wx
import wx.adv

import thor_alerts.config as config
import thor_alerts.ui as ui
from thor_alerts.notify import notify

# Implementing PreferencesDialog
class ThorAlertsPreferencesDialog(ui.PreferencesDialog):
    def __init__(self, parent, tskic:wx.adv.TaskBarIcon=None):
        ui.PreferencesDialog.__init__(self, parent)

        self.tskic = tskic

        self.input_HubURL.SetValue(config.get("hub_url", ""))
        self.checkbox_TrayIcon.SetValue(config.get("show_tray_icon", True))

    def on_notification_test(self, event):
        notify("Hello world!", "This is a test notification.", self.tskic)
