"""Subclass of MainFrame, which is generated by wxFormBuilder."""
import json
import os
import platform
import sys

import wx
import wx.adv

import thor_alerts.config as config
import thor_alerts.icons as icons
import thor_alerts.ui as ui
from thor_alerts.ThorAlertsPreferencesDialog import ThorAlertsPreferencesDialog as PreferencesDialog

os.chdir(os.path.dirname(os.path.abspath(__file__)))

intervals = (
    ('weeks', 604800),  # 60 * 60 * 24 * 7
    ('days', 86400),    # 60 * 60 * 24
    ('hours', 3600),    # 60 * 60
    ('minutes', 60),
    ('seconds', 1),
)

def display_time(seconds, granularity=2):
    result = []

    for name, count in intervals:
        value = seconds // count
        if value:
            seconds -= value * count
            if value == 1:
                name = name.rstrip('s')
            result.append("{} {}".format(value, name))
    return ', '.join(result[:granularity])

# Implementing MainFrame
class ThorAlertsMainFrame( ui.MainFrame ):
    def __init__( self, parent, tskic:wx.adv.TaskBarIcon=None ):
        ui.MainFrame.__init__( self, parent )

        self.tskic = tskic

        self.status_update_timer.Start(milliseconds=1000)
        self.update_tray_related_things()

    def on_close(self, event):
        if config.get("show_tray_icon"):
            self.Hide()
        else:
            self.on_quit(event)

    def on_quit(self, event):
        if self.tskic: self.tskic.Destroy()
        self.Destroy()

    def show_preferences(self, event):
        try:
            preferences = PreferencesDialog(None, self.tskic)
            if preferences.ShowModal() == wx.ID_OK:
                config.set("hub_url", preferences.input_HubURL.Value)
                config.set("show_tray_icon", preferences.checkbox_TrayIcon.IsChecked())
                if preferences.checkbox_TrayIcon.IsChecked():
                    self.tskic.SetIcon(wx.ArtProvider.GetBitmap(config.default_icon, wx.ART_OTHER), config.default_icon_tooltip)
                else:
                    self.tskic.RemoveIcon()
                self.update_tray_related_things()
        finally:
            # explicitly cause the dialog to destroy itself
            try:
                preferences.Destroy()
            finally:
                ## except when it fails...
                pass

    def update_tray_related_things(self):
        show_tray = config.get("show_tray_icon")
        if show_tray:
            self.close_button.Enable()
        else:
            self.close_button.Disable()

    def update_status( self, event ):
        # print(config.current_weather)
        weather = config.current_weather.get('weather', {})
        self.thor_status_label.SetLabelText(json.dumps(weather))
        self.weather_headline.SetLabelText(weather.get('headline', 'Unknown'))
        if platform.platform == "Linux":
            # self.weather_icon.SetBitmap(wx.ArtProvider.GetBitmap(
            #     icons.get_by_yr(weather.get('conditions', 'weather-none-available')).get('freedesktop'),
            #     size=wx.Size(64, 64)))
            # self.tskic.SetIcon(wx.ArtProvider.GetBitmap(
            #     icons.get_by_yr(weather.get('conditions', 'weather-none-available')).get('freedesktop'),
            #     size=wx.Size(64, 64)))
            self.weather_icon.SetBitmap(wx.ArtProvider.GetBitmap(
                icons.get_by_yr(weather.get('conditions', 'clearsky_day')).get('thoricon')))
            self.tskic.RemoveIcon()

            self.tskic.SetIcon(wx.ArtProvider.GetBitmap(
                icons.get_by_yr(weather.get('conditions', 'clearsky_day')).get('thoricon')), 'TEST')
        # else:
        #     self.weather_icon.SetBitmap(wx.ArtProvider.GetBitmap(
        #         icons.get_by_yr(weather.get('conditions', 'weather-none-available')).get('thoricon'),
        #         size=wx.Size(64, 64)))
        self.Layout()

