"""Subclass of MyFrame3, which is generated by wxFormBuilder."""

import os
import json

import wx

import ui

os.chdir(os.path.dirname(os.path.abspath(__file__)))

with open("../thor_alerts/icons.json", "r") as f:
    icons = json.load(f)

def get_by_yr(icon=None):
    return next((item for item in icons if item["yr"] == icon), {})

def get_by_thoricon(icon=None):
    return next((item for item in icons if item["thoricon"] == icon), {})

def get_by_freedesktop(icon=None):
    return next((item for item in icons if item["freedesktop"] == icon), {})

def get_by_fafree(icon=None):
    return next((item for item in icons if item["fa-free"] == icon), {})

# Implementing MyFrame3
class MyFrame3( ui.MyFrame3 ):
    def __init__( self, parent ):
        ui.MyFrame3.__init__( self, parent )
        self.RootId = None
        self.image_list = wx.ImageList(16, 16)
        self.icons.SetImageList(self.image_list)
        self.image_index = {'weather-none-available': self.image_list.Add(
            wx.ArtProvider.GetBitmap('weather-none-available', wx.ART_CMN_DIALOG, wx.Size(16, 16)))}
        self.update_tree()

    def change_item(self, event: wx.TreeEvent):
        # Saves the current icon to the list and changes to the new one
        icon = get_by_yr(self.icons.GetItemText(event.GetItem()))
        self.yr_icon.SetValue(icon.get('yr'))
        self.thoricon_value.SetValue(icon.get('thoricon'))
        self.freedesktop.SetValue(icon.get('freedesktop'))
        self.fa_free_value.SetValue(icon.get('fa-free'))

    def update_tree(self):
        if self.RootId:
            self.icons.DeleteAllItems()
            self.RootId = self.icons.AddRoot("Icons")
        else:
            self.RootId = self.icons.AddRoot("Icons")

        for icon in icons:
            new_item = self.icons.AppendItem(self.RootId, icon.get('yr'))
            icon = get_by_yr(self.icons.GetItemText(new_item))
            fd_icon = icon.get('freedesktop', 'weather-none-available')
            if not fd_icon: fd_icon = 'weather-none-available'
            if fd_icon not in self.image_index:
                self.image_index[fd_icon] = self.image_list.Add(wx.ArtProvider.GetBitmap(fd_icon, wx.ART_CMN_DIALOG, wx.Size(16, 16)))
            self.icons.SetItemImage(new_item, self.image_index.get(fd_icon, 0))
            # print("Image index {}".format(self.image_index.get(fd_icon, 0)))

    def new(self, event):
        self.icons.Unselect()
        self.yr_icon.SetValue("")
        self.thoricon_value.SetValue("")
        self.freedesktop.SetValue("")
        self.fa_free_value.SetValue("")

    def save(self, event):
        icon = get_by_yr(self.yr_icon.Value)
        if icon:
            index = icons.index(icon)
        else:
            index = None
            icon = {}

        icon['yr'] = self.yr_icon.Value
        icon['thoricon'] = self.thoricon_value.Value
        icon['freedesktop'] = self.freedesktop.Value
        icon['fa-free'] = self.fa_free_value.Value

        if index: icons[index] = icon
        else: icons.append(icon)

        with open("../thor_alerts/icons.json", "w") as f:
            json.dump(icons, f)
        self.update_tree()

    def remove(self, event):
        selected_icon = self.icons.GetSelection()
        icon = get_by_yr(self.icons.GetItemText(selected_icon))
        icons.remove(icon)
        self.update_tree()

    def update_icon( self, event ):
        self.icon_fd.SetBitmap(wx.ArtProvider.GetBitmap(self.freedesktop.Value, size=wx.Size(64, 64)))
        self.Layout()
